apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p-vol1
spec:
  volumeName: p-vol1
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc